// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8URhguNEtURGl0pce4q3Zz5qOoEyJkI',
    appId: '1:1056545890912:web:22f99522df953680f5d905',
    messagingSenderId: '1056545890912',
    projectId: 'tiao-oficina-mecanica',
    authDomain: 'tiao-oficina-mecanica.firebaseapp.com',
    storageBucket: 'tiao-oficina-mecanica.firebasestorage.app',
    measurementId: 'G-TP2RD2DJ7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9U1Tnm58iXEAFimcYYcYwj1tAnsLUf-8',
    appId: '1:1056545890912:android:b02a19e9672d262ff5d905',
    messagingSenderId: '1056545890912',
    projectId: 'tiao-oficina-mecanica',
    storageBucket: 'tiao-oficina-mecanica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByoqvu3mjKn-TSTafohaiP4WINMb1qoQA',
    appId: '1:1056545890912:ios:bd86176d70018d62f5d905',
    messagingSenderId: '1056545890912',
    projectId: 'tiao-oficina-mecanica',
    storageBucket: 'tiao-oficina-mecanica.firebasestorage.app',
    iosBundleId: 'com.tiao.tiaoOficina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByoqvu3mjKn-TSTafohaiP4WINMb1qoQA',
    appId: '1:1056545890912:ios:bd86176d70018d62f5d905',
    messagingSenderId: '1056545890912',
    projectId: 'tiao-oficina-mecanica',
    storageBucket: 'tiao-oficina-mecanica.firebasestorage.app',
    iosBundleId: 'com.tiao.tiaoOficina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK8URhguNEtURGl0pce4q3Zz5qOoEyJkI',
    appId: '1:1056545890912:web:95d2dce5499d06cff5d905',
    messagingSenderId: '1056545890912',
    projectId: 'tiao-oficina-mecanica',
    authDomain: 'tiao-oficina-mecanica.firebaseapp.com',
    storageBucket: 'tiao-oficina-mecanica.firebasestorage.app',
    measurementId: 'G-XP8XK8DV8L',
  );

}